"""Public typed Python SDK for CogniStore API v1."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .client import (
    DEFAULT_HTTP_TIMEOUT,
    DEFAULT_MAX_POLL_INTERVAL,
    DEFAULT_POLL_INTERVAL,
    SUPPORTED_OPERATION_IDS,
    TERMINAL_JOB_STATES,
    ClientConfig,
    CogniStoreClient,
)
from .errors import (
    APIError,
    AuthenticationError,
    CogniStoreError,
    ConflictError,
    JobFailedError,
    NotFoundError,
    PayloadTooLargeError,
    PermissionDeniedError,
    PollingTimeoutError,
    RangeNotSatisfiableError,
    RequestTimeoutError,
    ResponseContractError,
    ServerError,
    ServiceUnavailableError,
    TransportError,
    ValidationError,
)
from .models import (
    AccessPolicyFeature,
    AccessPolicyFeatureResponse,
    AskFilters,
    AskFiltersRequest,
    AskRequest,
    AskResponse,
    CatalogObject,
    CatalogObjectPage,
    CatalogScanRequest,
    DeleteObjectResponse,
    EmbeddingPolicyFeature,
    EmbeddingPolicyFeatureResponse,
    EmbeddingPolicyRuleConfig,
    GeneratedAnswer,
    GeneratedAnswerResponse,
    HeadObjectResponse,
    HealthResponse,
    JobState,
    JobStatus,
    JobStatusResponse,
    MimePolicyFeature,
    MimePolicyFeatureResponse,
    ObjectCitation,
    ObjectCitationResponse,
    ObjectDownload,
    ObjectResource,
    PageMetadata,
    PassageCitation,
    PassageCitationResponse,
    PassageMatch,
    PassageMatchResponse,
    PolicyConfig,
    PolicyEvaluationRequest,
    PolicyEvaluationResponse,
    PolicyFeatureProvenance,
    PolicyFeatureProvenanceResponse,
    PolicyFeatures,
    PolicyFeaturesResponse,
    PolicyFeatureState,
    PolicyRunRequest,
    ProviderDiagnostic,
    ProviderDiagnosticResponse,
    RetrievalResult,
    RetrievalResultResponse,
    RetrievedPassage,
    RetrievedPassageResponse,
    ScoreComponent,
    ScoreComponentResponse,
    ValidationIssue,
)

API_VERSION = 1

try:
    __version__ = version("cognistore")
except PackageNotFoundError:
    __version__ = "0+unknown"

__all__ = [
    "AccessPolicyFeature",
    "AccessPolicyFeatureResponse",
    "APIError",
    "API_VERSION",
    "AskFilters",
    "AskFiltersRequest",
    "AskRequest",
    "AskResponse",
    "AuthenticationError",
    "CatalogObject",
    "CatalogObjectPage",
    "CatalogScanRequest",
    "ClientConfig",
    "CogniStoreClient",
    "CogniStoreError",
    "ConflictError",
    "DEFAULT_HTTP_TIMEOUT",
    "DEFAULT_MAX_POLL_INTERVAL",
    "DEFAULT_POLL_INTERVAL",
    "DeleteObjectResponse",
    "EmbeddingPolicyFeature",
    "EmbeddingPolicyFeatureResponse",
    "EmbeddingPolicyRuleConfig",
    "GeneratedAnswer",
    "GeneratedAnswerResponse",
    "HeadObjectResponse",
    "HealthResponse",
    "JobFailedError",
    "JobState",
    "JobStatus",
    "JobStatusResponse",
    "MimePolicyFeature",
    "MimePolicyFeatureResponse",
    "NotFoundError",
    "ObjectCitation",
    "ObjectCitationResponse",
    "ObjectDownload",
    "ObjectResource",
    "PageMetadata",
    "PassageCitation",
    "PassageCitationResponse",
    "PassageMatch",
    "PassageMatchResponse",
    "PayloadTooLargeError",
    "PermissionDeniedError",
    "PolicyConfig",
    "PolicyEvaluationRequest",
    "PolicyEvaluationResponse",
    "PolicyFeatureProvenance",
    "PolicyFeatureProvenanceResponse",
    "PolicyFeatureState",
    "PolicyFeatures",
    "PolicyFeaturesResponse",
    "PolicyRunRequest",
    "PollingTimeoutError",
    "ProviderDiagnostic",
    "ProviderDiagnosticResponse",
    "RangeNotSatisfiableError",
    "RequestTimeoutError",
    "ResponseContractError",
    "RetrievalResult",
    "RetrievalResultResponse",
    "RetrievedPassage",
    "RetrievedPassageResponse",
    "SUPPORTED_OPERATION_IDS",
    "ScoreComponent",
    "ScoreComponentResponse",
    "ServerError",
    "ServiceUnavailableError",
    "TERMINAL_JOB_STATES",
    "TransportError",
    "ValidationError",
    "ValidationIssue",
    "__version__",
]
