{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cognistore.fullname" . }}
  labels:
    {{- include "cognistore.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "cognistore.name" . }}
  policyTypes: [Ingress, Egress]
  ingress: {{ if not .Values.networkPolicy.ingress }}[]{{ end }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress: {{ if and (not .Values.networkPolicy.egress) (not .Values.networkPolicy.dns.enabled) }}[]{{ end }}
    {{- if .Values.networkPolicy.dns.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.namespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    {{- end }}
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
