{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cognistore.fullname" . }}-api
  labels:
    {{- include "cognistore.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
{{- end }}
