"""Durable background jobs for CogniStore."""

from .models import (
    DeadLetterDisposition,
    DeadLetterNotFoundError,
    DeadLetterReceipt,
    DeadLetterRecord,
    DeadLetterRecordError,
    DeadLetterRedriveError,
    EnqueueReceipt,
    InvalidJobError,
    JobContext,
    JobEnvelope,
    JobEnvelopeError,
    QueueHealth,
    QueueSaturatedError,
    RedriveReceipt,
)
from .nats_queue import NatsJetStreamConfig, NatsJetStreamQueue
from .retry import (
    ErrorClassification,
    FailureCategory,
    RetryableJobError,
    RetryPolicy,
    TerminalJobError,
    classify_job_error,
)
from .runtime import (
    AsyncWorker,
    JobCoordinator,
    JobExecution,
    WorkerConfig,
    WorkerSnapshot,
    WorkerState,
)
from .scheduler import (
    PeriodicScheduler,
    ScheduledJob,
    ScheduledJobDefinition,
    ScheduledRunCoordinator,
    ScheduleRegistry,
    SQLiteScheduleStore,
    default_schedule_registry,
    load_schedule_config,
)

__all__ = [
    "AsyncWorker",
    "DeadLetterDisposition",
    "DeadLetterNotFoundError",
    "DeadLetterReceipt",
    "DeadLetterRecord",
    "DeadLetterRecordError",
    "DeadLetterRedriveError",
    "EnqueueReceipt",
    "ErrorClassification",
    "FailureCategory",
    "JobContext",
    "JobCoordinator",
    "JobEnvelope",
    "JobEnvelopeError",
    "JobExecution",
    "InvalidJobError",
    "NatsJetStreamConfig",
    "NatsJetStreamQueue",
    "QueueHealth",
    "QueueSaturatedError",
    "RedriveReceipt",
    "PeriodicScheduler",
    "RetryPolicy",
    "RetryableJobError",
    "ScheduledJob",
    "ScheduledJobDefinition",
    "ScheduledRunCoordinator",
    "ScheduleRegistry",
    "SQLiteScheduleStore",
    "TerminalJobError",
    "WorkerConfig",
    "WorkerSnapshot",
    "WorkerState",
    "classify_job_error",
    "default_schedule_registry",
    "load_schedule_config",
]
